Converting numerical data to categorical data

In [147]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd

In [148]:
data = pd.read_csv("titanic_dataset.csv")
data.sample(4)
x = data[['Age','Fare']]

In [115]:
x.isnull().sum()

Age     177
Fare      0
dtype: int64

In [122]:
from sklearn.model_selection import train_test_split
xtrain,xtest = train_test_split(x,test_size=0.2)
print(xtrain.shape)
print(xtest.shape)

(712, 2)
(179, 2)

In [123]:
from sklearn.impute import SimpleImputer
smp = SimpleImputer()

xtrain_trans = smp.fit_transform(xtrain)
xtest_trans = smp.transform(xtest)

In [124]:
print(xtrain_trans)
print("\n\n")
print(xtest_trans)

[[ 21.       8.4333]
 [ 22.      49.5   ]
 [ 58.     146.5208]
 ...
 [ 22.       7.775 ]
 [ 40.5      7.75  ]
 [ 32.5     13.    ]]



[[ 27.          12.475     ]
 [ 36.          13.        ]
 [ 40.         153.4625    ]
 [ 26.          16.1       ]
 [ 29.51094571   7.7333    ]
 [ 28.           7.8958    ]
 [ 29.51094571   0.        ]
 [ 29.           7.0458    ]
 [ 36.          24.15      ]
 [ 42.          27.        ]
 [ 50.           8.05      ]
 [ 29.51094571   7.05      ]
 [ 33.          90.        ]
 [ 29.          10.5       ]
 [ 29.51094571   7.8958    ]
 [ 29.51094571  16.1       ]
 [ 22.           7.125     ]
 [  0.75        19.2583    ]
 [ 29.51094571  56.4958    ]
 [ 29.51094571  25.925     ]
 [  1.          46.9       ]
 [ 35.          52.        ]
 [ 29.51094571   7.75      ]
 [ 51.          61.3792    ]
 [ 16.           8.05      ]
 [  1.          39.        ]
 [ 51.          12.525     ]
 [ 47.          25.5875    ]
 [ 29.51094571   7.8792    ]
 [ 33.          20.525     ]
 [ 51.           7.0542    ]
 [ 35.           7.8958    ]
 [ 21.           7.25      ]
 [ 21.           7.7958    ]
 [ 45.5         28.5       ]
 [ 61.           6.2375    ]
 [ 50.         133.65      ]
 [ 45.          35.5       ]
 [ 59.           7.25      ]
 [ 65.          26.55      ]
 [ 23.           7.55      ]
 [ 29.51094571  21.6792    ]
 [ 28.          13.        ]
 [ 19.          14.5       ]
 [ 56.          30.6958    ]
 [ 65.          61.9792    ]
 [  7.          26.25      ]
 [  0.67        14.5       ]
 [  4.          27.9       ]
 [ 29.51094571   7.2292    ]
 [ 56.          35.5       ]
 [ 15.           7.2292    ]
 [ 33.           7.8958    ]
 [ 19.          26.        ]
 [ 29.51094571  15.5       ]
 [  5.          27.75      ]
 [ 20.           7.05      ]
 [ 32.           7.925     ]
 [ 51.          77.9583    ]
 [ 28.          35.5       ]
 [ 25.          30.        ]
 [ 10.          24.15      ]
 [  4.          11.1333    ]
 [ 16.           7.775     ]
 [ 29.          15.2458    ]
 [ 24.          65.        ]
 [  3.          21.075     ]
 [ 29.51094571  15.05      ]
 [ 30.           8.05      ]
 [  4.          31.275     ]
 [ 46.          26.        ]
 [ 36.          12.875     ]
 [ 25.           7.775     ]
 [ 37.           7.925     ]
 [ 70.          10.5       ]
 [ 28.          47.1       ]
 [ 29.51094571   7.225     ]
 [ 39.          55.9       ]
 [ 30.           7.25      ]
 [ 38.          71.2833    ]
 [ 29.51094571   0.        ]
 [ 34.          13.        ]
 [ 44.           7.925     ]
 [ 18.         262.375     ]
 [ 27.           7.8958    ]
 [ 25.          55.4417    ]
 [ 19.           0.        ]
 [ 29.51094571  19.9667    ]
 [ 33.          53.1       ]
 [ 27.          14.4542    ]
 [ 36.5         26.        ]
 [ 29.51094571  25.4667    ]
 [ 29.51094571  25.4667    ]
 [ 16.          26.        ]
 [ 47.          34.0208    ]
 [ 30.           7.2292    ]
 [ 48.           7.8542    ]
 [ 18.          23.        ]
 [ 22.           9.        ]
 [ 32.           7.75      ]
 [ 19.          36.75      ]
 [ 23.          10.5       ]
 [ 40.           7.8958    ]
 [ 15.           7.225     ]
 [ 42.           8.4042    ]
 [ 63.          77.9583    ]
 [ 29.51094571 110.8833    ]
 [ 32.          15.85      ]
 [ 29.51094571  69.55      ]
 [ 29.51094571  69.55      ]
 [ 80.          30.        ]
 [ 19.          91.0792    ]
 [ 14.         120.        ]
 [ 29.51094571  31.        ]
 [ 39.          31.275     ]
 [ 37.          29.7       ]
 [ 54.          26.        ]
 [ 34.          21.        ]
 [ 30.5          8.05      ]
 [  4.          16.7       ]
 [ 29.51094571   8.7125    ]
 [ 35.          83.475     ]
 [  6.          31.275     ]
 [ 52.          78.2667    ]
 [ 12.          11.2417    ]
 [ 31.          10.5       ]
 [ 11.          18.7875    ]
 [ 24.          16.1       ]
 [ 29.51094571  56.4958    ]
 [ 29.51094571  39.6       ]
 [ 32.          56.4958    ]
 [ 18.          11.5       ]
 [ 45.          26.55      ]
 [ 29.51094571   7.55      ]
 [ 70.          71.        ]
 [ 38.           8.6625    ]
 [  1.          39.6875    ]
 [ 29.51094571  15.1       ]
 [ 21.           8.6625    ]
 [ 32.           8.05      ]
 [ 20.           9.225     ]
 [  5.          19.2583    ]
 [ 42.          26.        ]
 [ 29.51094571  26.55      ]
 [ 33.           8.6542    ]
 [ 29.51094571  24.15      ]
 [ 60.          75.25      ]
 [ 29.51094571  15.5       ]
 [  9.          27.9       ]
 [ 40.          13.        ]
 [ 31.         164.8667    ]
 [ 29.51094571   8.05      ]
 [  2.          39.6875    ]
 [ 20.           8.6625    ]
 [ 42.          13.        ]
 [ 29.          21.075     ]
 [ 58.         113.275     ]
 [ 36.          17.4       ]
 [ 45.           6.975     ]
 [ 29.51094571   8.1375    ]
 [  5.          12.475     ]
 [ 28.          13.        ]
 [ 36.          26.3875    ]
 [ 29.51094571   8.4583    ]
 [ 29.51094571  23.45      ]
 [ 29.51094571 221.7792    ]
 [ 28.5         16.1       ]
 [ 26.           7.8875    ]
 [  4.          13.4167    ]
 [ 21.          34.375     ]
 [ 23.          11.5       ]
 [ 47.          15.        ]
 [ 39.           7.925     ]
 [ 28.          15.85      ]
 [ 19.           8.05      ]
 [ 21.           7.925     ]
 [ 29.51094571 227.525     ]
 [ 30.          31.        ]
 [ 34.          10.5       ]]

# Binning

we use sklearn's KBinsDiscretizer and try different strategy

In [125]:
from sklearn.preprocessing import KBinsDiscretizer

In [126]:
K_bin = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='quantile')

In [127]:
xtrain_trs = K_bin.fit_transform(xtrain_trans)
xtest_trs = K_bin.transform(xtest_trans)

In [132]:
print(xtrain_trs[0:5],"\n\n",xtrain_trans[0:5])

[[2. 3.]
 [2. 8.]
 [8. 9.]
 [1. 3.]
 [5. 1.]]

 [[ 21.           8.4333    ]
 [ 22.          49.5       ]
 [ 58.         146.5208    ]
 [ 20.           8.05      ]
 [ 29.51094571   7.75      ]]

# Binarization

Converting Continous value to discrete values

In [134]:
from sklearn.preprocessing import Binarizer

In [141]:
data2 = pd.read_csv("C:\\Users\\Geetanshu Dev\\Documents\\csv for Ml\\titanic_dataset.csv")
data2.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [143]:

x = data2['Age']
xtrains,xtests = train_test_split(x,test_size=0.2)
print(xtrains,xtests)
print("\n\n")
print(xtrains.shape)
print(xtests.shape)

115    21.0
538     NaN
673    31.0
324     NaN
20     35.0
       ...
36      NaN
840    20.0
668    43.0
356    22.0
482    50.0
Name: Age, Length: 712, dtype: float64 649    23.0
245    44.0
248    37.0
369    24.0
651    18.0
       ...
1      38.0
648     NaN
855    18.0
339    45.0
409     NaN
Name: Age, Length: 179, dtype: float64



(712,)
(179,)

In [146]:
bin = Binarizer(copy=False)
xtrain_btrs = bin.fit_transform(xtrain_trans)
xtest_btrs = bin.transform(xtest_trans)

print(xtrain_btrs)
print("\n\n")
print(xtest_btrs)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]



[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]